#ifndef __board_Custom_SMT32F746G_DISCO__
#define __board_Custom_SMT32F746G_DISCO__


#include "Board/eosBoard_STM32F746G_DISCO.h"


#if defined(DISPLAY_ADAFRUIT_SSD1306_128x64_D098)

// Opcions generals del display
#define DISPLAY_IMAGE_WIDTH       128  // Amplada en pixels
#define DISPLAY_IMAGE_HEIGHT      64   // Alçada en pixels
#define DISPLAY_COLOR_FORMAT      ColorFormat::l1  // Format de color
#define DISPLAY_IMAGE_BUFFER      0xC0000000

// Opcions especifiques del controlador
#define DISPLAY_SSD1306_INTERFACE  DISPLAY_SSD1306_INTERFACE_SPI

#define DISPLAY_RST_PORT          ARDUINO_D0_PORT
#define DISPLAY_RST_PIN			  ARDUINO_D0_PIN

#define DISPLAY_DC_PORT           ARDUINO_D1_PORT
#define DISPLAY_DC_PIN            ARDUINO_D1_PIN

#define DISPLAY_CS_PORT           ARDUINO_D2_PORT
#define DISPLAY_CS_PIN            ARDUINO_D2_PIN

#define DISPLAY_SCK_PORT          ARDUINO_SPI_SCK_PORT
#define DISPLAY_SCK_PIN           ARDUINO_SPI_SCK_PIN
#define DISPLAY_SCK_AF			  ARDUINO_SPI_SCK_AF

#define DISPLAY_MOSI_PORT         ARDUINO_SPI_MOSI_PORT
#define DISPLAY_MOSI_PIN          ARDUINO_SPI_MOSI_PIN
#define DISPLAY_MOSI_AF           ARDUINO_SPI_MOSI_AF

#define DISPLAY_SPI_CHANNEL       HAL_SPI_CHANNEL_2


#endif


// Control del pin INT
//
#define VCNL4020_INT_PORT         HAL_GPIO_PORT_C
#define VCNL4020_INT_PIN          HAL_GPIO_PIN_7
#define VCNL4020_INT_EXTI_LINE    HAL_EXTI_LINE_7
#define VCNL4020_INT_EXTI_PORT    HAL_EXTI_PORT_C
#define VCNL4020_INT_IRQ          HAL_INT_VECTOR_EXTI7
#define VCNL4020_INT_PRIORITY     HAL_INT_PRIORITY_15
#define VCNL4020_INT_SUBPRIORITY  HAL_INT_SUBPRIORITY_0

#define VCNL4020_I2C_SCL_PORT     ARDUINO_I2C_SCL_PORT
#define VCNL4020_I2C_SCL_PIN      ARDUINO_I2C_SCL_PIN

#define VCNL4020_I2C_SDA_PORT     ARDUINO_I2C_SDA_PORT
#define VCNL4020_I2C_SDA_PIN      ARDUINO_I2C_SDA_PIN

#define VCNL4020_I2C_CHANNEL      ARDUINO_I2C_CHANNEL

#define VCNL4020_I2C              I2C_1
#define VCNL4020_PIN_SCL          PIN_B8
#define VCNL4020_PIN_SDA          PIN_B9
#define VCNL4020_PIN_INT          PIN_C7
#define VCNL4020_EXTI             EXTI_7


#endif // __board_Custom_STM32F746G_DISCO__

