// -----------------------------------------------------------------------
// Generated by FsmCompiler v1.1
// Finite state machine compiler tool
// Copyright 2015-2020 Rafael Serrano (rsr.openware@gmail.com)
//
// Warning. Don't touch. Changes will be overwritten!
//
// -----------------------------------------------------------------------

#ifndef __MACHINECONTEXT_H
#define __MACHINECONTEXT_H


#include "eos.h"
#include "Services/Fsm/eosFsmContextBase.h"


namespace app {

    class Context: public eos::FsmContextBase {
        public:
            Context();
        public:
            void start();
            void end();
            void onSW1_ON();
            void onSW2_ON();
            void onSW3_ON();
            void onTMR1_TIMEOUT();
    };

}


#endif // __MACHINECONTEXT_H
