// -----------------------------------------------------------------------
// Generated by FsmCompiler v1.1
// Finite state machine compiler tool
// Copyright 2015-2020 Rafael Serrano (rsr.openware@gmail.com)
//
// Warning. Don't touch. Changes will be overwritten!
//
// -----------------------------------------------------------------------

#include "MachineContext.h"
#include "MachineState.h"


namespace app {

    Context::Context() {
    }

    void Context::start() {
        setState(WaitingSW1::getInstance());
    }

    void Context::end() {
    }

    void Context::onSW1_ON() {
        static_cast<State*>(getState())->onSW1_ON(this);
    }

    void Context::onSW2_ON() {
        static_cast<State*>(getState())->onSW2_ON(this);
    }

    void Context::onSW3_ON() {
        static_cast<State*>(getState())->onSW3_ON(this);
    }

    void Context::onTMR1_TIMEOUT() {
        static_cast<State*>(getState())->onTMR1_TIMEOUT(this);
    }

}
