// -----------------------------------------------------------------------
// Generated by FsmCompiler v1.1
// Finite state machine compiler tool
// Copyright 2015-2020 Rafael Serrano (rsr.openware@gmail.com)
//
// Warning. Don't touch. Changes will be overwritten!
//
// -----------------------------------------------------------------------


#include "MachineState.h"
#include "MachineContext.h"


namespace app {

    Context::Context() {
    }

    void Context::start() {
        doLED1Off();
        doLED2Off();
        doLED3Off();
        doLED1Off();
        setState(WaitingSW1::getInstance());
    }

    void Context::end() {
    }

    void Context::onSW1Pressed() {
        static_cast<State*>(getState())->onSW1Pressed(this);
    }

    void Context::onSW2Pressed() {
        static_cast<State*>(getState())->onSW2Pressed(this);
    }

    void Context::onSW3Pressed() {
        static_cast<State*>(getState())->onSW3Pressed(this);
    }

    void Context::onTMR1TimeOut() {
        static_cast<State*>(getState())->onTMR1TimeOut(this);
    }

}
