// -----------------------------------------------------------------------
// Generated by FsmCompiler v1.1
// Finite state machine compiler tool
// Copyright 2015-2020 Rafael Serrano (rsr.openware@gmail.com)
//
// Warning. Don't touch. Changes will be overwritten!
//
// -----------------------------------------------------------------------


#include "MachineState.h"
#include "MachineContext.h"


namespace app {

    State::State(
        Context* context) :
        eos::FsmStateBase(context) {
    }

    void State::enter() {
    }

    void State::exit() {
    }

    void State::transition_SW1Pressed(const SW1Arguments* args)() {
    }

    void State::transition_SW2Pressed() {
    }

    void State::transition_SW3Pressed() {
    }

    WaitingSW1::WaitingSW1(
        Context* context) :
        State(context) {
    }

    void WaitingSW1::enter() {
        Context* ctx = static_cast<Context*>(getContext());
        MyStateMachine* owner = ctx->getOwner();
        owner->doLED1On();
    }

    void WaitingSW1::transition_SW1Pressed(const SW1Arguments* args)() {
        Context* ctx = static_cast<Context*>(getContext());
        MyStateMachine* owner = ctx->getOwner();
    }

    WaitingSW2::WaitingSW2(
        Context* context) :
        State(context) {
    }

    void WaitingSW2::enter() {
        Context* ctx = static_cast<Context*>(getContext());
        MyStateMachine* owner = ctx->getOwner();
        owner->doLED2On();
    }

    void WaitingSW2::transition_SW2Pressed() {
        Context* ctx = static_cast<Context*>(getContext());
        MyStateMachine* owner = ctx->getOwner();
        if (true) {
            ctx->beginTransition();
            owner->doLED2Off();
            ctx->endTransition(ctx->getStateInstance(Context::StateID::WaitingSW3));
        }
    }

    WaitingSW3::WaitingSW3(
        Context* context) :
        State(context) {
    }

    void WaitingSW3::enter() {
        Context* ctx = static_cast<Context*>(getContext());
        MyStateMachine* owner = ctx->getOwner();
        owner->doLED3On();
    }

    void WaitingSW3::transition_SW3Pressed() {
        Context* ctx = static_cast<Context*>(getContext());
        MyStateMachine* owner = ctx->getOwner();
        if (true) {
            ctx->beginTransition();
            owner->doLED3Off();
            ctx->endTransition(ctx->getStateInstance(Context::StateID::WaitingSW1));
        }
    }

}
