// -----------------------------------------------------------------------
// Generated by FsmCompiler v1.1
// Finite state machine compiler tool
// Copyright 2015-2020 Rafael Serrano (rsr.openware@gmail.com)
//
// Warning. Don't touch. Changes will be overwritten!
//
// -----------------------------------------------------------------------


#include "MachineState.h"
#include "MachineContext.h"


namespace app {

    State::State() {
    }

    void State::onSW1Pressed(
        Context* context) {
    }

    void State::onSW2Pressed(
        Context* context) {
    }

    void State::onSW3Pressed(
        Context* context) {
    }

    void State::onTMR1TimeOut(
        Context* context) {
    }

    WaitingSW1* WaitingSW1::instance = nullptr;

    WaitingSW1::WaitingSW1() {
    }

    WaitingSW1* WaitingSW1::getInstance() {
        if (instance == nullptr) instance = new WaitingSW1();
        return instance;
    }

    void WaitingSW1::onSW1Pressed(
        Context* context) {
        if (true) {
            context->doLED1Off();
            context->doLED1Off();
            context->doLED3Off();
            context->setState(WaitingSW2::getInstance());
        }
    }

    WaitingSW2* WaitingSW2::instance = nullptr;

    WaitingSW2::WaitingSW2() {
    }

    WaitingSW2* WaitingSW2::getInstance() {
        if (instance == nullptr) instance = new WaitingSW2();
        return instance;
    }

    void WaitingSW2::onSW2Pressed(
        Context* context) {
        if (true) {
            context->doLED1Off();
            context->doLED2Off();
            context->setState(WaitingSW3::getInstance());
        }
    }

    WaitingSW3* WaitingSW3::instance = nullptr;

    WaitingSW3::WaitingSW3() {
    }

    WaitingSW3* WaitingSW3::getInstance() {
        if (instance == nullptr) instance = new WaitingSW3();
        return instance;
    }

    void WaitingSW3::onSW3Pressed(
        Context* context) {
        if (true) {
            context->doLED2Off();
            context->doLED3Off();
            context->doTMR1Start();
            context->setState(WaitingTMR1::getInstance());
        }
    }

    WaitingTMR1* WaitingTMR1::instance = nullptr;

    WaitingTMR1::WaitingTMR1() {
    }

    WaitingTMR1* WaitingTMR1::getInstance() {
        if (instance == nullptr) instance = new WaitingTMR1();
        return instance;
    }

    void WaitingTMR1::onTMR1TimeOut(
        Context* context) {
        if (true) {
            context->doLED3Off();
            context->doLED1Off();
            context->setState(WaitingSW1::getInstance());
        }
    }

}
