// -----------------------------------------------------------------------
// Generated by FsmCompiler v1.1
// Finite state machine compiler tool
// Copyright 2015-2020 Rafael Serrano (rsr.openware@gmail.com)
//
// Warning. Don't touch. Changes will be overwritten!
//
// -----------------------------------------------------------------------

#ifndef __MACHINECONTEXT_H
#define __MACHINECONTEXT_H


#include "appMachineConfig.h"


namespace app {

    class Context: public eos::FsmContextBase {
        public:
            Context();
        public:
            void start();
            void end();
            void onSW1Pressed();
            void onSW2Pressed();
            void onSW3Pressed();
            void onTMR1TimeOut();
            void doLED1Off();
            void doLED2Off();
            void doLED3Off();
            void doTMR1Start();
    };

}


#endif // __MACHINECONTEXT_H
